### ISSUE TITLE
Missing release notes for v0.5.0

### ISSUE THREAD

**Issue by laughedelic** [ohnosequences/fastarious#15]
@eparejatobes 
I see the notes on Github releases page, but I don't see the `notes/0.5.0.markdown` file. How have you managed to do a release without it?

**Comment by eparejatobes** [comment]
You closed #12 :laughing:

**Comment by laughedelic** [comment]
LOL :laughing: 
Sorry. I thought that it was stale PR. Do you still have the branch? Then you can just merge it and push.

**Comment by laughedelic** [comment]
btw, I prefer to merge the release PR and then do the release. This way the tags are not messed up: first `archive/you/pr` then `v0.5.0`.

**Comment by eparejatobes** [comment]
Done in #12, closing
